language: perl

sudo: true

dist: bionic

env:
  - PREREQS="Module::Build rlib Test::More DB_File XML::DOM::XPath Bio::DB::GenBank Bio::Restriction::Analysis"

after_failure:
  - cat /home/travis/.cpanm/work/*/build.log

install:
  # Prerequisites
  # libdb-dev (Berkeley DB headers) seems to be needed by BioPerl
  # By running cpanm this way without testing rather than using ./Build,
  # we save *a lot* of time
  - sudo apt-get install -y libdb-dev
  - "cpanm --notest --force $PREREQS"

script:
  - perl Build.PL && ./Build && ./Build test

perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
