language: perl

sudo: false

env:
  - PREREQS="Module::Build"

after_failure:
  - cat /home/travis/.cpanm/work/*/build.log

install:
  # Prerequisites
  - "cpanm $PREREQS" && perl ./Build.PL && ./Build installdeps

perl:
  - "5.20"
  - "5.18"
  # - "5.16"
  # - "5.14"
  # - "5.12"
  # - "5.10"
